/**
 * Standardized error codes used throughout the application.
 * Used by services to throw specific, identifiable errors.
 * Each code maps to an HTTP status code and default message in errorConfig.ts
 */
export enum ErrorCode {
  // Authentication (4xx)
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",

  // Authorization (4xx)
  FORBIDDEN = "FORBIDDEN",
  OWNER_ACCESS_REQUIRED = "OWNER_ACCESS_REQUIRED",
  RIDER_ACCESS_REQUIRED = "RIDER_ACCESS_REQUIRED",
  ADMIN_ACCESS_REQUIRED = "ADMIN_ACCESS_REQUIRED",

  // Validation (4xx)
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_FIELD = "MISSING_FIELD",
  INVALID_ROLE = "INVALID_ROLE",
  INVALID_PHONE = "INVALID_PHONE",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  INVALID_STATUS = "INVALID_STATUS",

  // Conflicts (4xx)
  USER_EXISTS = "USER_EXISTS",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  PHONE_EXISTS = "PHONE_EXISTS",
  RESTAURANT_EXISTS = "RESTAURANT_EXISTS",

  // Not Found (4xx)
  NOT_FOUND = "NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
  MENU_ITEM_NOT_FOUND = "MENU_ITEM_NOT_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  CART_NOT_FOUND = "CART_NOT_FOUND",
  RIDER_NOT_FOUND = "RIDER_NOT_FOUND",

  // Ownership (4xx)
  NOT_RESTAURANT_OWNER = "NOT_RESTAURANT_OWNER",
  NOT_ORDER_OWNER = "NOT_ORDER_OWNER",
  NOT_CART_OWNER = "NOT_CART_OWNER",

  // Server errors (5xx)
  DATABASE_ERROR = "DATABASE_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
